### ISSUE TITLE
Internal links in legislation

### ISSUE THREAD

**Issue by mariyabb** [africanlii/liiweb#146]
Links to other legislation cited should point to namiblii versions of legislation.
e.g. in https://new.namiblii.org/akn/na/act/gn/2020/233/eng@2020-10-21#defn-term-hospital 
Act No. 36 of 1994 should take us to the https://namiblii.org/akn/na/act/1994/36  (or the new.namiblii.org equivalent for now) @longhotsummer

**Comment by longhotsummer** [comment]
We can do this by specifying `resolver=https://new.namiblii.org` when importing the legislation into liiweb.

The issue blocking this is that most works are referenced by work, not expression. eg. `/akn/na/act/1994/36` and the API module interferes with this right now. It should look for the most recent expression and redirect to that. Instead, it gives up and returns an ugly JSON 404.

**Comment by longhotsummer** [comment]
Let me see if I can fix this.

**Comment by longhotsummer** [comment]
This will be fixed when legislation is next updated.
