### ISSUE TITLE
Include section number in the link of a section / part / chapter in the TOC

### ISSUE THREAD

**Issue by mariyabb** [africanlii/liiweb#165]
As a user of legislation, I would like to easily view the section number in addition to the heading of a section in the TOC of legislation.  Legislation is cited with a section number more frequently than with the full section heading

Include section number in the TOC of legislation, so each link to a section is preceded with the section number
![image](https://user-images.githubusercontent.com/44869669/106775811-1f15c480-664c-11eb-977a-0641d334d3d7.png)

**Comment by longhotsummer** [comment]
Can you link to where you're seeing this? This should only happen if there is no number for that section.

**Comment by mariyabb** [comment]
There are section numbers: https://new.ulii.org/akn/ug/act/2013/12/eng@2013-11-01
It does not happen in Namibia: https://namiblii.org/akn/na/act/2003/8/eng@2016-10-25

**Comment by longhotsummer** [comment]
This is an issue on the Laws.Africa side, I'll ask Edith to take a look.

**Comment by mariyabb** [comment]
This has been resolved.
