### ISSUE TITLE
Filefield paths are not generated properly

### ISSUE THREAD

**Issue by mariyabb** [africanlii/liiweb#180]
Filefield paths are incorrectly showing as temporary
See Download PDF from https://ulii.org/ug/judgment/court-appeal-uganda/2019/8 leads us to https://ulii.org/system/temporary?file=filefield_paths/2019-ugca-8.pdf 

![image](https://user-images.githubusercontent.com/44869669/108096530-bf76da80-7089-11eb-8400-0a956024262f.png)

**Comment by roger-cts** [comment]
Was occurring due to active updating not happening when fields that fell part of the download file field path were edited. Have enabled and no longer occuring
