### ISSUE TITLE
Uploading PDFs for legislation returns an error

### ISSUE THREAD

**Issue by longhotsummer** [africanlii/liiweb#181]
The site contains a legislation node type. A piece of legislation can change over time, and we store the different legislation versions as different Drupal revisions for a node. A developer wrote an adjustment to the Drupal REST API to allow us to read and update the revisions easily. Without the REST API, we cannot update historical versions of a piece of legislation.

The API is documented here: https://github.com/africanlii/liiweb/tree/master/docs/jsonapi

A specific URL format allows us to update different versions. For example:

* http://liiweb.test/akn/za/act/1900/00/eng@1900-01-01 -- this is the english (eng) version of act "00" of "1900" (.../act/1900/00/...) at the date 1900-01-01 (1 Jan 1900).
* http://liiweb.test/akn/za/act/1900/00/eng@1920-02-02 -- this is the same as the above, but at date 1920-02-02.

We associate a PDF version of each piece of legislation. Each historical version has its own PDF version.

We upload a PDF in two steps (see documentation here):

1. upload the file to get a file ID
2. attach the file to an existing node

The files are stored in S3.

## The bug

When we try to attach a file to an existing node (step 2), we get this error:

```
LogicException: The controller result claims to be providing relevant cache metadata, but leaked metadata was detected. Please ensure you are not rendering content too early. Returned object class: Drupal\jsonapi\ResourceResponse. in Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext() (line 154 of /app/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php).
```

You can follow the instructions at https://github.com/africanlii/liiweb/tree/master/docs/jsonapi#attaching-files-to-an-expression to reproduce the bug

**Comment by Hayk-web** [comment]
I need to spend several hours reading the documentation and reproducing the issue. I will get back to you, once I have more info.

**Comment by Hayk-web** [comment]
I have read the documentation and reproduced the issue. Now working on a solution.
