### ISSUE TITLE
As a user of Gazette, I would like to see the PDF of the Gazette in PDFjs instead of the text currently stored in Body

### ISSUE THREAD

**Issue by mariyabb** [africanlii/liiweb#182]
Hide the Body field in Full view display and replace with a PDFjs view of the PDF.  Keep the Download PDF link as it currently is

Affected: Individual gazette page e.g. https://ulii.org/gazettes/ug-government-gazette-dated-2017-04-07-no-21

**Comment by longhotsummer** [comment]
Bear in mind that google indexes that first page, but not PDF.js, and some gazettes are huge (100s of MBs), which is why we don't do this in Gazettes.Africa.

But we could also be smarter about this.

**Comment by mariyabb** [comment]
Good point, Greg, re Google. 
PDFjs can be set to display only the first page, which should solve the 100MB gazette issue
and then we can keep the Body below the PDF? I just want the user to see the clean first page, first.

**Comment by longhotsummer** [comment]
Seems reasonable, although I suspect PDF.js downloads the entire PDF in any case.

**Comment by roger-cts** [comment]
The 1-page version of pdf.js is not working correctly currently on the site and is the current hold up. Looking into it.

**Comment by mariyabb** [comment]
@Hayk-web See Roger's problem displaying only 1 page of the PDF in PDFjs. See example page in the Issue. We require the Display to show in the following order:
Download PDF
The first page of the PDF in PDF.js (new element on the page)
Body as it currently is
