### ISSUE TITLE
Fix distorted Search block in top right corner when enabling Better filters to handle JQuery UI picker

### ISSUE THREAD

**Issue by mariyabb** [africanlii/liiweb#192]
Enable JQuery UI picker for the Custom Date field under better filters in the PG:Search view.  (https://ulii.org/admin/structure/views/view/liiweb_search/edit/page_search) 
![search3](https://user-images.githubusercontent.com/44869669/108366601-3bdff980-7201-11eb-82b1-2094b1ab1d28.PNG)
![search4](https://user-images.githubusercontent.com/44869669/108366622-400c1700-7201-11eb-82b0-fa4bf5e67b47.PNG)

The change distorts the look of the search box in the top right corner of pages (e.g. https://ulii.org/ug/judgment/commercial-court-uganda/2021/3 and https://ulii.org/judgments)

![searchblock1](https://user-images.githubusercontent.com/44869669/108366634-439f9e00-7201-11eb-8f46-26c86d7f6e0f.PNG)

Fix the display of the search block, while retaining Better Exposed Filters

**Comment by Hayk-web** [comment]
Done. PR has been opened.
