### ISSUE TITLE
Judgment Date field missing from Judgment content creation

### ISSUE THREAD

**Issue by roger-cts** [africanlii/liiweb#194]
The Judgment date field is missing from the form when creating Judgment entities. There is also distortion on some of the boxs where they are exiting containers as seen below.
![missing_date](https://user-images.githubusercontent.com/58774261/108385889-c847e780-7214-11eb-80b6-f7eeac92c599.jpg)

Looking into what could be the cause i've found this issue is present on Both Namiblii and Ulii but not on the master branch. The master branch differs from Namiblii by only 5 commits. Within these the [Header Search](https://github.com/africanlii/liiweb/tree/header_search)
commit seems to be the only one with css changes, which I believe could be the result of the issue.

**Comment by roger-cts** [comment]
Looking at it again the distorted box by Law Report Citations is still present in master, so that part is unrelated. The Judgment Date field is however present.

**Comment by Hayk-web** [comment]
The issue has been fixed and pushed to the "header-search" branch.
