### ISSUE TITLE
Incorrect handling of the request URI when loading revision in API

### ISSUE THREAD

**Issue by cristiroma** [africanlii/liiweb#206]
The API controller is incorrectly handling request URIs. Adding GET parameters to the request affects loading the correct revision.

Works: https://example.org/akn/za/act/1900/00/eng@1900-01-01
Does not work: https://example.org/akn/za/act/1900/00/eng@1900-01-01?extra_param=1

**Comment by longhotsummer** [comment]
I do remember seeing this and thought I had fixed it 🤷

**Comment by cristiroma** [comment]
Yes, indeed it is fixed in a couple of places. I suppose I fixed it everywhere :)

**Comment by longhotsummer** [comment]
I believe this is fixed.
