### ISSUE TITLE
Unexpected error displaying PIT versions of legislation 

### ISSUE THREAD

**Issue by mariyabb** [africanlii/liiweb#246]
Unexpected error displaying a point-in-time version of legislation (see screenshot).  It looks related to this point in the code:
https://github.com/africanlii/liiweb/blob/master/web/modules/custom/liiweb_legislation/liiweb_legislation.module#L227

`$repeal` will never be valid there. What it should be is the latest version of the current node

![image](https://user-images.githubusercontent.com/44869669/112487760-a72f6500-8d85-11eb-8720-a1eaaa6d245d.png)

**Comment by cristiroma** [comment]
Yes, I think this is a copy/paste error.

**Comment by longhotsummer** [comment]
@cristiroma Would you be able to assist with replacing this with a link to the latest revision? Alternatively, it can be to the FRBR URI without any date, which will always resolve to the latest.

**Comment by mariyabb** [comment]
@Hayk-web please could you fix as per Greg's instructions above.

**Comment by Hayk-web** [comment]
https://github.com/africanlii/liiweb/pull/259
