### ISSUE TITLE
Fix reference to government gazette in legislation content

### ISSUE THREAD

**Issue by mariyabb** [africanlii/liiweb#247]
In the legislation content type, links to the Government gazette in the Preface of the act are incorrectly constructed - see highlighted link also https://ulii.org/akn/ug/act/si/2020/83/eng@2020-06-26  - Government Gazette No.39 links to https://edit.laws.africa**.laws.africa**/works/akn/ug/act/si/2020/83/media/publication/ug-act-si-2020-83-publication-document.pdf  where there is a redundant .laws.africa in the URL

![image](https://user-images.githubusercontent.com/44869669/112617551-c84b9080-8e2d-11eb-8486-73b0aaef7856.png)

**Comment by mariyabb** [comment]
@longhotsummer same issue in the PDF here: https://media.ulii.org/files/legislation/akn-ug-act-2011-9-eng-2011-06-10.pdf  So, I am not sure if this is a liiweb issue.

**Comment by longhotsummer** [comment]
Hmm, this looks like an Indigo issue.
