### ISSUE TITLE
Multiple Case Numbers

### ISSUE THREAD

**Issue by roger-cts** [africanlii/liiweb#262]
We need to have multiple case numbers. Case numbers are made up of 3 fields ( field_case_number, field_case_number_numeric and field_matter_type). Currently, the  field_case_number is a computed field running the following within the field itself instead of a custom module:
`//Sets old to the old case number value of the node if it exists.
$old = $entity->field_case_number_old->value;
$casecurrent = $entity->field_case_number->value;
$none = 'No Case No';

if($old != NULL && $casecurrent == NULL)
{
//Sets the value of judgment number to the override value if one has been entered.
$value = $old;
}
elseif($entity->field_matter_type->isEmpty() || $entity->field_case_number_numeric->isEmpty() || $entity->field_case_number_year->isEmpty())
{
//Sets the value to "Unknown" if any of the 3 fields is empty.
$value = $none;
}
else
{
$value = $entity->field_matter_type->entity->label() . "-" . $fields['field_case_number_year'][0]['value'] . "/" . $fields['field_case_number_numeric'][0]['value'];
}`

We need this computation to work for multiple values, ie... create an array of case numbers from the corresponding field_case_number_numeric, field_case_number_year, and field_matter_type.

We've tried using the following code in both custom module and within the field itself : 
`//Sets old to the old case number value of the node if it exists.
$old = $entity->field_case_number_old->value;
$casecurrent = $entity->field_case_number->value;
$none = 'No Case No';

if($old != NULL && $casecurrent == NULL)
{
//Sets the value of judgment number to the override value if one has been entered.
$value = $old;
}
elseif($entity->field_matter_type->isEmpty() || $entity->field_case_number_numeric->isEmpty() || $entity->field_case_number_year->isEmpty())
{
$value = $none;
}
else
{
$count = count($entity->field_case_number_numeric);
$values=array();
for($x=0;$x<$count;$x++)
{
$values[$x] = $entity->field_matter_type->entity->label() . "-" . $fields['field_case_number_year'][$x]['value'] . "/" . $fields['field_case_number_numeric'][$x]['value'];
$value = $values[$delta];
}

}`
With this, we managed to successfully create the multiple case numbers from the multiple component fields, but it would create a large array of blanks along with it.

**Comment by roger-cts** [comment]
@Hayk-web please let me know if you have any queries about this. Also please don't spend more than 2-3hours on this, if it's going to be a long or complicated fix we'll just move over to using rules to produce the field.

**Comment by mariyabb** [comment]
@roger-cts please close this issue if this has now been deployed successfully.
