### ISSUE TITLE
PIT version of Acts do not store PDF of that PIT

### ISSUE THREAD

**Issue by mariyabb** [africanlii/liiweb#287]
For example see https://ulii.org/akn/ug/act/statute/1996/13/eng@2011-06-10  does not have a PDF attachment

**Comment by longhotsummer** [comment]
https://ulii.org/akn/ug/act/2005/17/eng@2010-06-25 has the same issue.

**Comment by longhotsummer** [comment]
Loading the JSON for an old PIT revision shows that there are no files: http://ulii.org/jsonapi/node/legislation/134f465b-32ff-4ebd-97cc-43a0bd10eba0/field_files?resourceVersion=id%3A16256

```javascript
{
    "jsonapi": {
        "version": "1.0",
        "meta": {
            "links": {
                "self": {
                    "href": "http://jsonapi.org/format/1.0/"
                }
            }
        }
    },
    "data": [],
    "links": {
        "self": {
            "href": "http://ulii.org/jsonapi/node/legislation/134f465b-32ff-4ebd-97cc-43a0bd10eba0/field_files?resourceVersion=id%3A16256"
        }
    }
}
```

**Comment by longhotsummer** [comment]
The indigo code is definitely pushing the PDFs for the different points in time. I will have to check if we're calling the API incorrectly.

**Comment by longhotsummer** [comment]
Seems to be working.
