### ISSUE TITLE
Add new taxonomy field in judgment for ISO Country Code

### ISSUE THREAD

**Issue by mariyabb** [africanlii/liiweb#309]
this is necessary for multi-jurisdictional sites, such as AfricanLII

**Comment by longhotsummer** [comment]
Should we include the same field for legislation?

Is this a two or three letter country code? Indigo uses two. 

Greg
--
(iPhone)

**Comment by mariyabb** [comment]
@longhotsummer I thought about our issue with legislation in South Africa. Agreed. Let's make this field available to the legislation content type, too @roger-cts . 
The country code should standardize to the Indigo one. It is not so currently on the new AfricanLII (which is why we need this to be done today/tomorrow), but because this is a taxonomy field, we can easily adjust it across tags.
