### ISSUE TITLE
Drupal doesn't allow titles longer than 255 chars

### ISSUE THREAD

**Issue by longhotsummer** [africanlii/liiweb#32]
Some of our works have very long names, eg. "Application of the provisions of section 18 of the Native Administration Proclamation, 1928 (Proclamation 15 of 1928) (South-West Africa), and of the regulations published under Government Notice 70 of 1954 (South-West Africa) in the Territory of South-West Africa" - see https://edit.laws.africa/works/na/act/gn/1974/r192/

Can this field be expanded, or do we need to truncate the title?

**Comment by cristiroma** [comment]
It can be expanded @stefanbutura ?
